// Generated by gencpp from file test_pkg/Time_order.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_TIME_ORDER_H
#define TEST_PKG_MESSAGE_TIME_ORDER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct Time_order_
{
  typedef Time_order_<ContainerAllocator> Type;

  Time_order_()
    : t(0.0)
    , number(0)  {
    }
  Time_order_(const ContainerAllocator& _alloc)
    : t(0.0)
    , number(0)  {
  (void)_alloc;
    }



   typedef double _t_type;
  _t_type t;

   typedef uint8_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::test_pkg::Time_order_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::Time_order_<ContainerAllocator> const> ConstPtr;

}; // struct Time_order_

typedef ::test_pkg::Time_order_<std::allocator<void> > Time_order;

typedef boost::shared_ptr< ::test_pkg::Time_order > Time_orderPtr;
typedef boost::shared_ptr< ::test_pkg::Time_order const> Time_orderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::Time_order_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::Time_order_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::Time_order_<ContainerAllocator1> & lhs, const ::test_pkg::Time_order_<ContainerAllocator2> & rhs)
{
  return lhs.t == rhs.t &&
    lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::Time_order_<ContainerAllocator1> & lhs, const ::test_pkg::Time_order_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Time_order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Time_order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Time_order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Time_order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Time_order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Time_order_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::Time_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd8c27f370df30bc9f25b37d76a2c791";
  }

  static const char* value(const ::test_pkg::Time_order_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd8c27f370df30bcULL;
  static const uint64_t static_value2 = 0x9f25b37d76a2c791ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::Time_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/Time_order";
  }

  static const char* value(const ::test_pkg::Time_order_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::Time_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 t\n"
"uint8 number\n"
;
  }

  static const char* value(const ::test_pkg::Time_order_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::Time_order_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Time_order_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::Time_order_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::Time_order_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_TIME_ORDER_H
